server:
  port: 8083
  servlet:
    context-path: /

# jpa config
spring:
  application:
    name: training-service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/master?characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: a123456b

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
    register-with-eureka: true
    fetch-registry: true